version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    open-pull-requests-limit: 5
    ignore:
    - dependency-name: "@galihru/tvmai"
      versions: [">0.1.5"]
